on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - run: curl -L https://github.com/flix/flix/releases/download/v0.14.3/flix.jar > flix.jar
    - run: java -jar flix.jar test

