on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Test Flix
      id: flix-test
      uses: mlutze/flix-test-action@v0.1
      with:
        flix-version: 'v0.14.3'

